### PR TITLE
Very basic functional MVP

### PR DESCRIPTION
**Pull request by brunosan**
I went ahead and did the most basic thing.
- Using roberta embeddings, not GPT. since it's free and fast. (and much worse but good for testing).
- Not using GPT to enrich the query.
- Using cosine similarity to find the single sentence of most similarity on each doc.
- Use ngrams to find within the doc the ngram of most relevance.

- Simple Gradio interface.

Overall, technically works, but the top results are not that good. I suspect is partly the worse models, but also that the query might need to be enriched.
Screenshot 2023-03-18 at 18 21 14

### CODE REVIEW

**Comment by brunosan** [comment]
hey, lol, better already than WB search site:
Screenshot 2023-03-18 at 18 31 11

**Comment by gsVAM** [comment]
Nicely done bruno!

**Comment by gsVAM** [comment]
Nicely done bruno!

**Comment by brunosan** [comment]
Oh boy. Totally got into the itch... and totally gave up on TypeScript 😀

I'll add you to a new clean repo

**Comment by gsVAM** [comment]
I started using a really sweet library called haystack do this.  Then I
just asked chatGPT to give me the code 😄…you can check it out in my branch
under “src.”

**Pull request merged**
